global:
  name: "Profile Stealthy at 20pps"
  description: '20pps with peacetime lists, extracting file with 100 lines of credit card data'
  public_resolver: "129.206.100.126"

timing:
  duration: 100000
  peacetime_duration: 0

allowlist:
  global_allowlist_path: "./allowlists/tranco.txt"
  local_allowlist_dir: "./allowlists/local/20pps"

traffic:
  pcap_path: "./pcaps"
  benign:
    enabled: true
    pcap: "merged_mar2.pcap"
    pps: 20

  wildcard:
    enabled: false
    pcap: "bigwildcard.pcap"
    pps: 15

  tunnel:
    replay: false
    docker: true
    pcap: "roguerobin.pcap"
    pps: 0
    toolname: "dnsexfiltrator"
    tunneling_domains: ["dnsexfil.com", "dnsexfil.it", "dnsexfil.fr", "dnsexfil.us", "dnsexfil.co", "dnsexfil.pl", "dnsexfil.to", "dnsexfil.xyz", "dnsexfil.shop", "dnsexfil.gr"]
    tunnel_server_ip: 192.168.4.4 #has to be in right subnet
    expansion_factor: 4

output:
  logdir: "./results/"