global:
  name: "Baseline Exfiltration"
  description: 'DNSExfiltrator extracting a credit card file (FD=0.1s, RD=0, SL=63, ENC=Base32, SEQ=PLAIN, DC=1, DQ=0)'
  public_resolver: "129.206.100.126"

timing:
  duration: 240
  peacetime_duration: 0

allowlist:
  allowlist_path: "./allowlists/tranco.txt"

traffic:
  pcap_path: "./pcaps"
  benign:
    enabled: true
    pcap: "merged.pcap"
    pps: 20

  wildcard:
    enabled: false
    pcap: "bigwildcard.pcap"
    pps: 15

  tunnel:
    replay: false
    docker: true
    pcap: "roguerobin.pcap"
    pps: 5
    toolname: "dnsexfiltrator"
    tunneling_domains: [ "dnsexfil.com" ]
    tunnel_server_ip: 192.168.4.4 #has to be in right subnet
    expansion_factor: 1.6

output:
  logdir: "./results/"