services:
  resolver:
    container_name: resolver
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Berlin
    ports:
      - 9999:53/tcp
      - 9999:53/udp
    volumes:
      - ./resolver/config:/etc/bind
      - ./resolver/cache:/var/cache/bind
      - ./resolver/records:/var/lib/bind
    networks:
      client-network:
        ipv4_address: 172.16.0.2
      internet:
        ipv4_address: 10.1.1.1
    restart: unless-stopped

  tcpreplay:
    build: ./pcap-replayer
    container_name: pcap-replayer
    network_mode: service:resolver
    volumes:
      - ${PCAP_PATH}:/app
    cap_add:
      - NET_ADMIN
      - NET_RAW
    entrypoint: ["sh", "-c", "ip link add replay0 type dummy &&
      ip link set replay0 up &&
      echo '✓ replay0 created and ready' && tail -f /dev/null"
      ]

  dnscollector:
    container_name: dnscollector
    image: dmachard/dnscollector:latest
    network_mode: service:resolver
    user: root
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dns-collector/config/:/etc/dnscollector/
      - ./dns-collector/logs:/var/log/dnscollector
    restart: unless-stopped

  root-simulator:
    container_name: root-simulator
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Berlin
    volumes:
      - ./root-simulator/config:/etc/bind
      - ./root-simulator/cache:/var/cache/bind
      - ./root-simulator/records:/var/lib/bind
    networks:
      internet:
        ipv4_address: 10.5.5.5
    restart: unless-stopped

  tld-simulator:
    container_name: tld-simulator
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Berlin
    volumes:
      - ./tld-simulator/config:/etc/bind
      - ./tld-simulator/cache:/var/cache/bind
      - ./tld-simulator/records:/var/lib/bind
    networks:
      internet:
        ipv4_address: 10.10.10.10
      server-network:
        ipv4_address: 192.168.1.1
    restart: unless-stopped

  iodine-server:
    container_name: iodine-server
    build: ./iodine-server
    profiles: ["iodine"]
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      server-network:
        ipv4_address: 192.168.2.2
    restart: no
    entrypoint: ["iodined", "-f", "-c", "-P", "password123", "10.100.100.100", "tunnel.com"]

  iodine-client:
    container_name: iodine-client
    build: ./iodine-client
    profiles: ["iodine"]
    privileged: true
    cap_add:
      - NET_ADMIN
    dns:
      - 172.16.0.2
    networks:
      client-network:
        ipv4_address: 172.16.0.10
    restart: no
    entrypoint: ["iodine", "-f", "-r", "-P", "password123", "tunnel.com"]

  dnscat2-client:
    container_name: dnscat2-client
    profiles: ["dnscat2"]
    build: ./dnscat2-client
    volumes:
      - ./dnscat2-client/dnscat2:/dnscat2/
    entrypoint: ["./dnscat", "--dns", "domain=dnscat2-tunnel.com,type=AAAA", "--no-encryption"]
    networks:
      client-network:
        ipv4_address: 172.16.30.30
    dns:
      - 172.16.0.2

  dnscat2-server:
    container_name: dnscat2-server
    profiles: ["dnscat2"]
    build: ./dnscat2-server
    tty: true       
    stdin_open: true
    volumes:
      - ./dnscat2-server/dnscat2:/dnscat2/
    entrypoint: ["ruby", "./dnscat2.rb", "dnscat2-tunnel.com", "--security=open"]
    networks:
      server-network:
        ipv4_address: 192.168.3.3


networks:
  client-network:
    name: client-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
  server-network:
    name: server-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1
  internet:
    name: internet
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/8
        gateway: 10.0.0.1

