zone "tunnel.com" IN {
    type forward;
    forwarders { 10.5.5.5; };
};

zone "." IN {
    type forward;
    forwarders { 129.206.100.126; };
};

options {
    listen-on { any; };
    allow-query { any; };
    directory "/var/cache/bind";

};

server ::/0 { bogus yes; };