zone "tunnel.com" IN {
    type forward;
    forwarders { 192.168.2.2; };
};

options {
    listen-on { any; };
    allow-query { any; };
    directory "/var/cache/bind";

};

server ::/0 { bogus yes; };