global:
  server-identity: "dns-collector"
  trace:
    verbose: true
    log-malformed: true

pipelines:
  - name: sniffer
    afpacket-sniffer:
      port: 53
      device: ""              # alle Interfaces
      enable-defrag-ip: true
      chan-buffer-size: 65536
    transforms:
      filtering:
        keep-queryip-file: "/etc/dnscollector/ip_keeplist.txt"  # nur client-network IPs behalten
    routing-policy:
      forward: ["console-output", "logfile-json"]

  - name: sniffer_replay
    afpacket-sniffer:
      port: 53
      device: replay0
      enable-defrag-ip: true
      chan-buffer-size: 65536
    # kein transforms/filtering hier
    routing-policy:
      forward: ["console-output", "logfile-json"]


  - name: "console-output"
    stdout:
      mode: "text"

  - name: "logfile-json"
    logfile:
      file-path: /var/log/dnscollector/dnslogs.json
      mode: json
      max-files: 0
      max-size: 50000
