options {
    listen-on { any; };
    allow-query { any; };
    directory "/var/cache/bind";
    clients-per-query 10;
    max-clients-per-query 100;
    max-cache-size 512M;
    max-cache-ttl 3600;
    max-ncache-ttl 60;
    dnssec-validation auto;
    {VALIDATE_EXCEPT_BLOCK}
};

#no ipv6 as docker doesnt support it
server ::/0 { bogus yes; };

{ZONE_BLOCKS}

zone "." IN {
    type forward;
    forwarders { {PUBLIC_IP_RESOLVER}; };
};